server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wlfmiss/microservicecloud-config.git # 一定要使用https:// 开头 不要是git@开头 GitHub上面的git仓库名字



