server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.wlf.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: microservicecloud-dept
   datasource:
    # type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb03              # 数据库名称
    username: root
    password: P@ssw0rd
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#       defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:  #修改服务名称在注册中心的展示样式
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true #可以展示IP信息

info:
  app.name: wlf-microservicecloud
  company.name: www.wlf.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$